// This file is auto-generated by mockupPreviewPlugin.ts.
// Stub for typecheck — actual file is generated during Vite dev/build.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {};
